services:
  - type: web
    name: rgu-hub-backend
    env: python
    pythonVersion: 3.11.10

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    startCommand: gunicorn rguHub.wsgi:application --workers=2 --threads=2 --timeout=120

    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: rguHub.settings
      - key: ALLOWED_HOSTS
        value: "https://rgu-hub-backend-cubv.onrender.com"
      - key: LOG_LEVEL
        value: "INFO"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://rgu-hub-backend-cubv.onrender.com"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONPATH
        value: "."

    autoDeploy: true
